export const onboardingElements = {
  createWalletButton: 'Create a new wallet',
  importRecoveryPhraseButton: 'Import an existing wallet',
  useRecoveryPhraseButton: 'Use recovery phrase or private key',
  createNewRecoveryPhraseButton: 'Create new recovery phrase',
  showMyPhraseButton: 'I understood. Show my phrase.',
  copyToClipboardButton: 'Copy to clipboard',
  nextButton: 'Next',
  focusedInput: 'input:focus',
  phrasePrivateKey: 'Private key',
  phraseInput: '.sc-iAvgwm.kEpgcC',
  phraseCount24: '24 words',
  walletName: 'My wallet',
  phraseSelectChain: 'Select Chains',
  phraseAccountCreated: 'Account Created!',
  walletInput: 'input[name="name"]:focus',
  passwordInput: 'input[name="password"]',
  confirmPasswordInput: 'input[name="confirmPassword"]',
  submitWalletDataButton: 'button[type="submit"]',
  submitChainButton: 'button[type="button"]',
  finishButton: 'button[type="button"]',
  textAreaSelector: 'textbox',
  submitPhraseButton: '.sc-bZkfAO jGdbNJ',
};
