/*
 * Copyright (C) 2020 BOSONIC, Inc. All rights reserved.
 * 
 * BOSONIC is a trademark of BOSONIC, Inc.
 * 
 * References to third-party marks or brands are the property of their
 * respective owners. No rights or licenses are granted, express or implied,
 * unless set forth in a written agreement signed by BOSONIC, Inc.
 * Dissemination or reproduction of content contained herein is strictly
 * forbidden except as otherwise expressly permitted pursuant to a
 * written agreement signed by BOSONIC, Inc.
 * 
 * Date: 10/04/23 
 * Author(s): Diego Graf
 * -----------------------
 * Last Modified: 05/16/24
 * Modified By: Diego Graf
 * 
 */

const BOSONIC_CONSTANTS = require('../../support/bosonic.constants')
const ENVIRONMENT = require('../../support/bosonic.environments')

module.exports = Object.freeze({

  TASK: {
    GET_BALANCE_LENDER_BEFORE: 'getTotalBalanceLenderBefore',
    GET_BALANCE_BORROWER_BEFORE: 'getTotalBalanceBorrowerBefore',
    SET_ORDERID_LENDER: 'setOrderIdLender',
    GET_ORDERID_LENDER: 'getOrderIdLender',
    GET_BORROWER_BEARER: 'getBorrowerBearer',
    GET_LENDER_BEARER: 'getLenderBearer',
    SET_TRADE_BLOTTER_LENDER_QUANTITY_ROWS: 'setTradeBlotterLenderQuantityRows',
    GET_TRADE_BLOTTER_LENDER_QUANTITY_ROWS: 'getTradeBlotterLenderQuantityRows',
    SET_ROW_BLOTTER_LENDER: 'setRowBlotterLender',
    GET_ROW_BLOTTER_LENDER: 'getRowBlotterLender',
    SET_QTY2: 'setQty2',
    GET_QTY2: 'getQty2',
    GET_AUTOLIQUIDATION_PRICE: 'getAutoliquidationPrice',
    GET_ETH_SELLING_PRICE: 'getEthSellingPrice',
    GET_PRICE: 'getPrice',
    GET_ELAPSED_TIME: 'getElapsedTime',
    SET_BALANCE_LENDER_BEFORE: 'setTotalBalanceLenderBefore',
    SET_BALANCE_BORROWER_BEFORE: 'setTotalBalanceBorrowerBefore',
    SET_BALANCE_FEES_BEFORE: 'setTotalBalanceFeesBefore',
    SET_BORROWER_BEARER: 'setBorrowerBearer',
    SET_LENDER_BEARER: 'setLenderBearer',
    SET_FEES_BEARER: 'setFeesBearer',
    SET_TAKER_BEARER: 'setTakerBearer',
    GET_TAKER_BEARER: 'getTakerBearer',
    SET_ELAPSED_TIME: 'setElapsedTime',
    SET_PRICE: 'setPrice',
    SET_AUTOLIQUIDATION_PRICE: 'setAutoliquidationPrice',
    SET_ETH_SELLING_PRICE: 'setEthSellingPrice',
    SET_BTC_PRICE: 'setBtcPrice',
    GET_BTC_PRICE: 'getBtcPrice',
    SET_ETH_PRICE: 'setEthPrice',
    GET_ETH_PRICE: 'getEthPrice',
    SET_DIFF_ASSET_3: 'setDiffAsset3',
    GET_DIFF_ASSET_3: 'getDiffAsset3',
    SET_DIFF_ASSET_2: 'setDiffAsset2',
    GET_DIFF_ASSET_2: 'getDiffAsset2',
    SET_DIFF_ASSET_1: 'setDiffAsset1',
    GET_DIFF_ASSET_1: 'getDiffAsset1',
    SET_BORROWER_USDC_BALANCE_AFTER_REPO_BEFORE_PAYMENT: 'setBorrowerUSDCBalanceAfterRepoMatchBeforePayment',
    GET_BORROWER_USDC_BALANCE_AFTER_REPO_BEFORE_PAYMENT: 'getBorrowerUSDCBalanceAfterRepoMatchBeforePayment',
    SET_TODAY_DATE: 'setTodayDate',
    GET_TODAY_DATE: 'getTodayDate',
    SET_LEND_PRICE: 'setLendPrice',
    GET_LEND_PRICE: 'getLendPrice',
    SET_REPO_FEES: 'setRepoFees',
    GET_REPO_FEES: 'getRepoFees',
    SET_INTEREST_RECEIVED: 'setInterestReceived',
    GET_INTEREST_RECEIVED: 'getInterestReceived',
    SET_LAST_REPO_ID: 'setLastRepoId',
    GET_LAST_REPO_ID: 'getLastRepoId'
  },
  MESSAGE: {
    NO_ORDER_STUCK: "NO ORDERS STUCK"
  },
  URL: {
    URL_TM_BORROWER: ENVIRONMENT.BASE_URL_TRAD_1,
    URL_TM_LENDER: ENVIRONMENT.BASE_URL_TRAD_3,
    URL_TM_TAKER: ENVIRONMENT.BASE_URL_TRAD_1,
    URL_FEES: ENVIRONMENT.BASE_URL_SPREAD,
    PUBLIC_API: ENVIRONMENT.BASE_URL_BOSONIC_PUBLIC_API,
    QUERY_ALL_TRADEBLOTTER_TM: ENVIRONMENT.BASE_URL_TRAD_3 + "/rest/lmorder/queryAll?*Status=FILLED,REJECTED,CANCELLED,CONFIRMED,BLOCKCHAIN_REJECTED,REPLACED,EXPIRED&lmStatus=PARTFILL_COMPLETE,PARTFILL_OPEN,FILLED,REJECTED,CANCELLED,CLOSED**",
    INTERCEPTOR_OPEN_ORDER_BORROWER: ENVIRONMENT.BASE_URL_TRAD_1 + "rest/lmorder/queryAll?**",
    MATCH_ORDER_URL: ENVIRONMENT.BASE_URL_TRAD_3 + "/rest/lmorder"
  },
  USER: {
    USER_TM_BORROWER: ENVIRONMENT.USERS.TM1_REPO,
    USER_TM_LENDER: ENVIRONMENT.USERS.TM3_REPO,
    USER_FEES: ENVIRONMENT.USERS.REPO_FEES,
    USER_TM_TAKER: ENVIRONMENT.USERS.TM1
  },
  USER_FEES: ENVIRONMENT.USERS.REPO_FEES,
  USER_24H: {
    USER_TM_BORROWER: ENVIRONMENT.USERS.TM1_REPO_24H,
    USER_TM_LENDER: ENVIRONMENT.USERS.TM3_REPO_24H
  },
  USER_01A: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_01A,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_01A
  },
  USER_01B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_01B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_01B
  },
  USER_01C: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_01C,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_01C
  },
  USER_01D: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_01D,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_01D
  },
  USER_02A: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_02A,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_02A
  },
  USER_02B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_02B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_02B
  },
  USER_02C: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_02C,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_02C
  },
  USER_02D: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_02D,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_02D
  },
  USER_03A: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_03A,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_03A
  },
  USER_03B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_03B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_03B
  },
  USER_03C: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_03C,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_03C
  },
  USER_03D: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_03D,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_03D
  },
  USER_04A: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_04A,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_04A
  },
  USER_04B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_04B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_04B
  },
  USER_04C: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_04C,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_04C
  },
  USER_04D: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_04D,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_04D
  },
  USER_05B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_05B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_05B
  },
  USER_05C: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_05C,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_05C
  },
  USER_05D: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_05D,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_05D
  },
  USER_06B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_06B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_06B
  },
  USER_06C: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_06C,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_06C
  },
  USER_06D: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_06D,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_06D
  },
  USER_07B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_07B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_07B
  },
  USER_07C: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_07C,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_07C
  },
  USER_07D: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_07D,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_07D
  },
  USER_08B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_08B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_08B
  },
  USER_09B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_09B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_09B
  },
  USER_10B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_10B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_10B
  },
  USER_10C: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_10C,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_10C
  },
  USER_10D: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_10D,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_10D
  },
  USER_11B: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_11B,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_11B
  },
  USER_13: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_13,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_13
  },
  USER_14: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_14,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_14
  },
  USER_15: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_15,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_15
  },
  USER_16: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_16,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_16
  },
  USER_17: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_17,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_17
  },
  USER_18: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_18,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_18
  },
  USER_19: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_19,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_19
  },
  USER_20: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_20,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_20
  },
  USER_21: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_21,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_21
  },
  USER_22: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_22,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_22
  },
  USER_23: {
    BORROWER: ENVIRONMENT.USERS.TM1_REPO_23,
    LENDER: ENVIRONMENT.USERS.TM3_REPO_23
  },
  WIDGET: {
    REPO_RATES: BOSONIC_CONSTANTS.TRADER.WIDGETS.REPO_RATES,
    REPO_PANEL: BOSONIC_CONSTANTS.TRADER.WIDGETS.REPO_PANEL,
    REPO_POSITION: BOSONIC_CONSTANTS.TRADER.WIDGETS.REPO_POSITIONS,
    TRADER: BOSONIC_CONSTANTS.TRADER,
    TRADER_TRADE_BLOTTER: BOSONIC_CONSTANTS.TRADER.WIDGETS.TRADE_BLOTTER,
  },
  MISC: {
    STANDARD_PAGE_SIZE: 10,
    DECIMAL_PLACES: 6,
    FIFTY_PERCENT: 0.5,
    TENTH_PERCENT: 0.1,
    ONE_ORDER: 1
  },
  CLOSE_REPO_METHOD: {
    MANUAL: 'MANUAL',
    AUTOREVERT: 'AUTOREVERT'
  },
  USER_TYPE: {
    LENDER: 'Lender',
    BORROWER: 'Borrower',
    FEES: 'Fees'
  },
  SYMBOL: {
    U15_RPO: 'U15/RPO',
    U15_RPOS: 'U15/RPOS'
  },
  TYPE_TRADER: {
    LENDER: 'Lender',
    BORROWER: 'Borrower',
    FEES: 'Fees'
  }
})