name: E2E (cypress-action)

on:
  push:
  pull_request:
    branches: [master, dev]

concurrency:
  group:
    '${{ github.workflow }} @ ${{ github.event.pull_request.head.label ||
    github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  e2e:
    if:
      github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v2

      - name: Install pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # pin@v2.4.0

      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # pin@v3.8.1
        with:
          node-version: 18.16

      - name: Run anvil
        run: |
          docker-compose -f docker-compose.ci.yml --profile foundry up --build --detach
        env:
          ANVIL_FORK_URL: ${{ secrets.ANVIL_FORK_URL }}

      - name: Set pnpm cache directory
        run: pnpm config set store-dir .pnpm-store
        continue-on-error: true

      - name: Setup cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # pin@v2
        with:
          path: |
            .pnpm-store
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-pnpm-v1-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-v1-
        continue-on-error: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install linux deps
        run: |
          sudo apt-get install --no-install-recommends -y \
          fluxbox \
          xvfb

      - name: Run xvfb and fluxbox
        run: |
          Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
          fluxbox &
        env:
          DISPLAY: :0.0

      - name: Run e2e tests (cypress-action)
        uses: cypress-io/github-action@248bde77443c376edc45906ede03a1aba9da0462 # pin@v5.8.4
        with:
          start: pnpm start:server
          command: pnpm test:e2e:ci:cypress-action
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          spec: tests/e2e/specs/*
        env:
          CYPRESS_PRIVATE_KEY_WITH_FUNDS:
            ${{ secrets.CYPRESS_PRIVATE_KEY_WITH_FUNDS }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          DISPLAY: :0.0

      - name: Archive e2e artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # pin@v2
        if: always()
        with:
          name: e2e-artifacts
          path: |
            tests/e2e/videos
            tests/e2e/screenshots
        continue-on-error: true
